flags:
  groundhog-test:
    mysql: false
    sqlite: false
    postgresql: true
extra-package-dbs: []
packages:
- groundhog/
- examples/
- groundhog-inspector/
- groundhog-postgresql/
- groundhog-sqlite/
- groundhog-th/
- groundhog-test/
extra-deps: []
resolver: lts-13.0
