flags:
  groundhog-test:
    mysql: true
    sqlite: false
    postgresql: false
extra-package-dbs: []
packages:
- groundhog/
- examples/
- groundhog-inspector/
- groundhog-postgresql/
- groundhog-sqlite/
- groundhog-th/
- groundhog-test/
extra-deps: []
resolver: lts-13.0
