CREATE TABLE tbl1 (a INT, b BIGINT, c TEXT, d DOUBLE PRECISION, e TINYINT(1), f DATE, g TIME, h TIMESTAMP, j BLOB);
CREATE TABLE tbl2 (a YEAR(2), b YEAR(4), c VARCHAR(2), d BINARY(2), e VARBINARY(2));

