CREATE TABLE tbl1_not_mapped (id INTEGER PRIMARY KEY NOT NULL, a INTEGER);
CREATE TABLE tbl2 (b INTEGER NOT NULL REFERENCES tbl1_not_mapped (id));

CREATE TABLE tbl3_not_mapped (id1 INTEGER NOT NULL, id2 INTEGER NOT NULL, a INTEGER, PRIMARY KEY (id1, id2));

CREATE TABLE tbl4 (b1 INTEGER NOT NULL, b2 INTEGER NOT NULL, FOREIGN KEY (b1, b2) REFERENCES tbl3_not_mapped (id1, id2));
CREATE TABLE tbl5 (b1 INTEGER NOT NULL, b2 INTEGER NOT NULL, FOREIGN KEY (b1, b2) REFERENCES tbl3_not_mapped (id2, id1));
CREATE TABLE tbl6 (b1 INTEGER NOT NULL, b2 INTEGER NOT NULL, FOREIGN KEY (b2, b1) REFERENCES tbl3_not_mapped (id1, id2));
CREATE TABLE tbl7 (b1 INTEGER NOT NULL, b2 INTEGER NOT NULL, FOREIGN KEY (b2, b1) REFERENCES tbl3_not_mapped (id2, id1));
