CREATE TABLE tbl1 (a INT4, b INT8, c VARCHAR, d NUMERIC, e DATE, f BOOL, g TIME, h TIMESTAMP, j TIMESTAMPTZ, k FLOAT4, l FLOAT8, m BYTEA);
CREATE TABLE tbl2 (a NUMERIC(3, 2), b POINT, c LINE, d LSEG, e BOX, f PATH, g POLYGON, h CIRCLE);

