CREATE TABLE tbl1 (id INTEGER NOT NULL PRIMARY KEY, a INTEGER);
CREATE TABLE tbl2 (b VARCHAR NOT NULL REFERENCES tbl1 (id));

CREATE TABLE tbl3 (id1 INTEGER NOT NULL, id2 INTEGER NOT NULL, a INTEGER, PRIMARY KEY (id1, id2));
CREATE TABLE tbl4 (b1 VARCHAR NOT NULL, b2 VARCHAR NOT NULL, FOREIGN KEY (b1, b2) REFERENCES tbl3 (id1, id2));
