CREATE TABLE tbl1 (id INTEGER PRIMARY KEY NOT NULL, a INTEGER);
CREATE TABLE tbl2 (b INTEGER REFERENCES tbl1 (id));

CREATE TABLE tbl3 (id1 INTEGER NOT NULL, id2 INTEGER NOT NULL, a INTEGER, PRIMARY KEY (id1, id2));
CREATE TABLE tbl4 (b1 INTEGER, b2 INTEGER, FOREIGN KEY (b1, b2) REFERENCES tbl3 (id1, id2));

CREATE TABLE tbl5 (id1 INTEGER NOT NULL, id2 INTEGER NOT NULL, a INTEGER, PRIMARY KEY (id1, id2));
CREATE TABLE tbl6 (b1 INTEGER, b2 INTEGER NOT NULL, FOREIGN KEY (b1, b2) REFERENCES tbl5 (id1, id2));


CREATE TABLE tbl7 (a INTEGER NOT NULL, UNIQUE(a));
CREATE TABLE tbl8 (a INTEGER, FOREIGN KEY(a) REFERENCES tbl7(a));

CREATE TABLE tbl9 (a INTEGER, UNIQUE(a));
CREATE TABLE tbl10 (a INTEGER NOT NULL, FOREIGN KEY(a) REFERENCES tbl9(a));
