CREATE TABLE tbl1 (a INTEGER, b VARCHAR, c REAL, d BOOLEAN, e DATE, f TIME, g TIMESTAMP, h TIMESTAMP WITH TIME ZONE, j BLOB);
CREATE TABLE tbl2 (a AFFINITY_INT, b AFFINITY_CHAR, c AFFINITY_BLOB, d AFFINITY_REAL, e AFFINITY_NUMERIC);
